// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	context "context"

	model "github.com/luongtruong20201/bookmark-management/internal/models"
	mock "github.com/stretchr/testify/mock"
)

// Service is an autogenerated mock type for the Service type
type Service struct {
	mock.Mock
}

// CountBookmarks provides a mock function with given fields: ctx, userID
func (_m *Service) CountBookmarks(ctx context.Context, userID string) (int64, error) {
	ret := _m.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for CountBookmarks")
	}

	var r0 int64
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (int64, error)); ok {
		return rf(ctx, userID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) int64); ok {
		r0 = rf(ctx, userID)
	} else {
		r0 = ret.Get(0).(int64)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Create provides a mock function with given fields: ctx, description, url, userId
func (_m *Service) Create(ctx context.Context, description string, url string, userId string) (*model.Bookmark, error) {
	ret := _m.Called(ctx, description, url, userId)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 *model.Bookmark
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, string) (*model.Bookmark, error)); ok {
		return rf(ctx, description, url, userId)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string, string) *model.Bookmark); ok {
		r0 = rf(ctx, description, url, userId)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.Bookmark)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string, string) error); ok {
		r1 = rf(ctx, description, url, userId)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Delete provides a mock function with given fields: ctx, bookmarkID, userID
func (_m *Service) Delete(ctx context.Context, bookmarkID string, userID string) error {
	ret := _m.Called(ctx, bookmarkID, userID)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) error); ok {
		r0 = rf(ctx, bookmarkID, userID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GetBookmarks provides a mock function with given fields: ctx, userID, offset, limit
func (_m *Service) GetBookmarks(ctx context.Context, userID string, offset int, limit int) ([]*model.Bookmark, error) {
	ret := _m.Called(ctx, userID, offset, limit)

	if len(ret) == 0 {
		panic("no return value specified for GetBookmarks")
	}

	var r0 []*model.Bookmark
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, int, int) ([]*model.Bookmark, error)); ok {
		return rf(ctx, userID, offset, limit)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, int, int) []*model.Bookmark); ok {
		r0 = rf(ctx, userID, offset, limit)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*model.Bookmark)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, int, int) error); ok {
		r1 = rf(ctx, userID, offset, limit)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Update provides a mock function with given fields: ctx, bookmarkID, userID, description, url
func (_m *Service) Update(ctx context.Context, bookmarkID string, userID string, description string, url string) (*model.Bookmark, error) {
	ret := _m.Called(ctx, bookmarkID, userID, description, url)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 *model.Bookmark
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, string, string) (*model.Bookmark, error)); ok {
		return rf(ctx, bookmarkID, userID, description, url)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string, string, string) *model.Bookmark); ok {
		r0 = rf(ctx, bookmarkID, userID, description, url)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.Bookmark)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string, string, string) error); ok {
		r1 = rf(ctx, bookmarkID, userID, description, url)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewService creates a new instance of Service. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewService(t interface {
	mock.TestingT
	Cleanup(func())
}) *Service {
	mock := &Service{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
