// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// Healthcheck is an autogenerated mock type for the Healthcheck type
type Healthcheck struct {
	mock.Mock
}

// Check provides a mock function with given fields: _a0
func (_m *Healthcheck) Check(_a0 context.Context) (string, string, string) {
	ret := _m.Called(_a0)

	if len(ret) == 0 {
		panic("no return value specified for Check")
	}

	var r0 string
	var r1 string
	var r2 string
	if rf, ok := ret.Get(0).(func(context.Context) (string, string, string)); ok {
		return rf(_a0)
	}
	if rf, ok := ret.Get(0).(func(context.Context) string); ok {
		r0 = rf(_a0)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(context.Context) string); ok {
		r1 = rf(_a0)
	} else {
		r1 = ret.Get(1).(string)
	}

	if rf, ok := ret.Get(2).(func(context.Context) string); ok {
		r2 = rf(_a0)
	} else {
		r2 = ret.Get(2).(string)
	}

	return r0, r1, r2
}

// NewHealthcheck creates a new instance of Healthcheck. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewHealthcheck(t interface {
	mock.TestingT
	Cleanup(func())
}) *Healthcheck {
	mock := &Healthcheck{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
