// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	gin "github.com/gin-gonic/gin"
	mock "github.com/stretchr/testify/mock"
)

// Handler is an autogenerated mock type for the Handler type
type Handler struct {
	mock.Mock
}

// Create provides a mock function with given fields: c
func (_m *Handler) Create(c *gin.Context) {
	_m.Called(c)
}

// DeleteBookmark provides a mock function with given fields: c
func (_m *Handler) DeleteBookmark(c *gin.Context) {
	_m.Called(c)
}

// GetBookmarks provides a mock function with given fields: c
func (_m *Handler) GetBookmarks(c *gin.Context) {
	_m.Called(c)
}

// ImportBookmarks provides a mock function with given fields: c
func (_m *Handler) ImportBookmarks(c *gin.Context) {
	_m.Called(c)
}

// UpdateBookmark provides a mock function with given fields: c
func (_m *Handler) UpdateBookmark(c *gin.Context) {
	_m.Called(c)
}

// NewHandler creates a new instance of Handler. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewHandler(t interface {
	mock.TestingT
	Cleanup(func())
}) *Handler {
	mock := &Handler{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
