// Code generated by mockery v2.53.5. DO NOT EDIT.

package mocks

import (
	context "context"

	queue "github.com/luongtruong20201/bookmark-management/internal/services/queue"
	mock "github.com/stretchr/testify/mock"
)

// Service is an autogenerated mock type for the Service type
type Service struct {
	mock.Mock
}

// SendBookmarkJob provides a mock function with given fields: ctx, uid, bookmarks
func (_m *Service) SendBookmarkJob(ctx context.Context, uid string, bookmarks []*queue.ImportBookmarkInput) error {
	ret := _m.Called(ctx, uid, bookmarks)

	if len(ret) == 0 {
		panic("no return value specified for SendBookmarkJob")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, []*queue.ImportBookmarkInput) error); ok {
		r0 = rf(ctx, uid, bookmarks)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewService creates a new instance of Service. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewService(t interface {
	mock.TestingT
	Cleanup(func())
}) *Service {
	mock := &Service{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
